version: 0.2

phases:
  build:
    commands:
      - echo "Deploying Template1 stacks"

      - |
        for i in $(seq 1 8); do
          aws cloudformation deploy \
            --stack-name t1-stack-$i \
            --template-file template1.yaml \
            --region ap-south-1 \
            --capabilities CAPABILITY_NAMED_IAM
        done

      - echo "Deploying Template2 stacks"

      - |
        for i in $(seq 1 10); do
          aws cloudformation deploy \
            --stack-name t2-stack-$i \
            --template-file template2.yaml \
            --region ap-south-1 \
            --capabilities CAPABILITY_IAM
        done

  post_build:
    commands:
      - echo "All stack deployments completed"
